# Autogenerated wrapper script for pandoc_crossref_jll for x86_64-apple-darwin
export pandoc_crossref

JLLWrappers.@generate_wrapper_header("pandoc_crossref")
JLLWrappers.@declare_executable_product(pandoc_crossref)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        pandoc_crossref,
        "bin/pandoc-crossref",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
